package com.MealTable.meal_table.util;

public enum OrderStatus {
    BOOKING_IN_PROGRESS,
    BOOKED,
    CONFIRMED,
    DISPATCHED,
    DELIVERED,
    CANCEL_REQUESTED,
    CANCELLED,
    CANCEL_REJECTED,
    RETURN_REQUESTED,
    RETURN_REJECTED,
    OUT_FOR_RETURN_PICKUP,
    RETURNED
}
